version: "3.7"

services:
  pgadmin:
    image: leaderboard-pgadmin
    build: ./pgadmin
    ports:
      - '6552:80'
    networks:
      - backend
      - default
  db:
    image: db
    build: db
    networks:
      - backend
  # the unit test db uses the same postgres server image, but mounts a new data dir every time
  # the container starts. This means that data doesn't persist between container executions.
  # This is incredibly useful for ensuring fresh tests and managing migrations
  db-unit:
    image: db
    tmpfs: "/var/lib/postgresql/data:rw"
    networks:
      - backend

  web:
    image: leaderboard-web
    build: ../
    networks:
      - backend
      - default
    ports:
      - '5000:5000'
    volumes:
      - npm-cache:/root/.npm
    # needed for rsyslog to work  
    # privileged: true

networks:
  backend:
    driver: bridge

volumes:
  npm-cache:
    external: false
