version: "3.7"

services:
  db:
    image: db
    build: db
    networks:
      - backend
  # the unit test db uses the same postgres server image, but mounts a new data dir every time
  # the container starts. This means that data doesn't persist between container executions.
  # This is incredibly useful for ensuring fresh tests and managing migrations
  db-unit:
    image: db
    tmpfs: "/var/lib/postgresql/data:rw"
    networks:
      - backend

  web:
    image: web
    build: ../
    networks:
      - backend
    expose:
      - 5000
    volumes:
      - npm-cache:/root/.npm

networks:
  backend:
    driver: bridge

volumes:
  npm-cache:
    external: false
